### ISSUE TITLE
Getting error while installing

### ISSUE THREAD

**Issue by akshatknsl** [waiting-for-dev/devise-jwt#134]
I have configured the gem as per the steps, getting below error while starting the server.

```

/Library/Ruby/Gems/2.3.0/gems/devise-jwt-0.5.9/lib/devise/jwt/models/jwt_authenticatable.rb:14:in `<module:JwtAuthenticatable>': undefined method `class_methods' for Devise::Models::JwtAuthenticatable:Module (NoMethodError)
Did you mean?  class_eval
	from /Library/Ruby/Gems/2.3.0/gems/devise-jwt-0.5.9/lib/devise/jwt/models/jwt_authenticatable.rb:11:in `<module:Models>'
	from /Library/Ruby/Gems/2.3.0/gems/devise-jwt-0.5.9/lib/devise/jwt/models/jwt_authenticatable.rb:6:in `<module:Devise>'
	from /Library/Ruby/Gems/2.3.0/gems/devise-jwt-0.5.9/lib/devise/jwt/models/jwt_authenticatable.rb:5:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/devise-jwt-0.5.9/lib/devise/jwt/models.rb:3:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `block in require'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:232:in `load_dependency'
	from /Library/Ruby/Gems/2.3.0/gems/activesupport-4.1.6/lib/active_support/dependencies.rb:247:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/devise-jwt-0.5.9/lib/devise/jwt.rb:11:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:95:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:95:in `rescue in block in require'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:72:in `block in require'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `each'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.0/lib/bundler/runtime.rb:65:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/bundler-1.16.0/lib/bundler.rb:114:in `require'
	from /Users/embibe/MyWork/Embibe/Code/test_app_master_prod/config/application.rb:8:in `<top (required)>'
	from /Library/Ruby/Gems/2.3.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:79:in `require'
	from /Library/Ruby/Gems/2.3.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:79:in `block in server'
	from /Library/Ruby/Gems/2.3.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:76:in `tap'
	from /Library/Ruby/Gems/2.3.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:76:in `server'
	from /Library/Ruby/Gems/2.3.0/gems/railties-4.1.6/lib/rails/commands/commands_tasks.rb:40:in `run_command!'
	from /Library/Ruby/Gems/2.3.0/gems/railties-4.1.6/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:8:in `require'
	from bin/rails:8:in `<main>'

```

**Comment by waiting-for-dev** [comment]
It seems you are using rails `4.1`, while `class_methods` method in active support concern was introduced in [4.2](https://github.com/rails/rails/blob/4-2-stable/activesupport/CHANGELOG.md).

**Comment by waiting-for-dev** [comment]
Closing because rails 4.1 is not a supported rails version anymore.

**Comment by waiting-for-dev** [comment]
Anyway, @akshatknsl , if it is the only part on the library which is not compatible with 4.1 you won't have a hard time adapting the `:jwt_authenticatable` module in order not to use `class_methods` method. Feel free to ask for support here if needed.

**Comment by kejordan** [comment]
I could use some support with this issue as well.  The app I'm working on is actually stuck on Rails 3 (we're working on getting up to date).  If you have any hints to get started modifying the gem to work with Rails 3, it would be much appreciated.

**Comment by waiting-for-dev** [comment]
Hey @kejordan ,

IIRC you only need to modify this file: https://github.com/waiting-for-dev/devise-jwt/blob/master/lib/devise/jwt/models/jwt_authenticatable.rb

`class_methods` is not available on Rails 3. Instead, you should create the `ClassMethods` nested module: https://www.rubydoc.info/docs/rails/3.2.8/ActiveSupport/Concern
