### ISSUE TITLE
Runtime Error On Code Change

### ISSUE THREAD

**Issue by Petercopter** [waiting-for-dev/devise-jwt#182]
## Expected behavior
Request returns JWT in header

## Actual behavior
500 Error
```
RuntimeError (Could not find a valid mapping for #<User id: 21, jti: "a6c89bd9-a5a9-4192-b418-b3a388cb45ba"
```

## Steps to Reproduce the Problem
This appears to be coming from the upgrade to `0.8.0`. Maybe I should have opened this on `warden-jwt_auth`, because that's where it appears to be coming from. If I lock my versions, it works. 
```
gem 'devise-jwt', '0.6.0'
gem 'warden-jwt_auth', '0.4.2'
```

1. Start the server
2. Make a request
3. Change some Ruby code
5. Make another request
6. Error

## Debugging information

Full error
```
RuntimeError (Could not find a valid mapping for #<User id: 21, jti: "a6c89bd9-a5a9-4192-b418-b3a388cb45ba"...>):
  
devise (4.7.2) lib/devise/mapping.rb:46:in `find_scope!'
devise (4.7.2) lib/devise/controllers/rememberable.rb:31:in `forget_me'
devise (4.7.2) lib/devise/hooks/forgetable.rb:9:in `block in <top (required)>'
warden (1.2.8) lib/warden/hooks.rb:15:in `block in _run_callbacks'
warden (1.2.8) lib/warden/hooks.rb:10:in `each'
warden (1.2.8) lib/warden/hooks.rb:10:in `_run_callbacks'
warden (1.2.8) lib/warden/manager.rb:52:in `_run_callbacks'
warden (1.2.8) lib/warden/proxy.rb:274:in `block in logout'
warden (1.2.8) lib/warden/proxy.rb:272:in `each'
warden (1.2.8) lib/warden/proxy.rb:272:in `logout'
devise (4.7.2) lib/devise/controllers/sign_in_out.rb:98:in `sign_out_all_scopes'
devise (4.7.2) lib/devise/controllers/helpers.rb:257:in `handle_unverified_request'
actionpack (6.0.3.2) lib/action_controller/metal/request_forgery_protection.rb:242:in `verify_authenticity_token'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:428:in `block in make_lambda'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:200:in `block (2 levels) in halting'
actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:201:in `block in halting'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:513:in `block in invoke_before'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:513:in `each'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:513:in `invoke_before'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:134:in `run_callbacks'
actionpack (6.0.3.2) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (6.0.3.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `block in instrument'
activesupport (6.0.3.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
activesupport (6.0.3.2) lib/active_support/notifications.rb:180:in `instrument'
actionpack (6.0.3.2) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (6.0.3.2) lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
activerecord (6.0.3.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
actionpack (6.0.3.2) lib/abstract_controller/base.rb:136:in `process'
actionview (6.0.3.2) lib/action_view/rendering.rb:39:in `process'
actionpack (6.0.3.2) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (6.0.3.2) lib/action_controller/metal.rb:254:in `dispatch'
actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:33:in `serve'
actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:49:in `block in serve'
actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `each'
actionpack (6.0.3.2) lib/action_dispatch/journey/router.rb:32:in `serve'
actionpack (6.0.3.2) lib/action_dispatch/routing/route_set.rb:834:in `call'
bullet (6.1.0) lib/bullet/rack.rb:15:in `call'
rack-attack (6.3.1) lib/rack/attack.rb:97:in `call'
warden-jwt_auth (0.5.0) lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
warden-jwt_auth (0.5.0) lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
rack (2.2.3) lib/rack/builder.rb:244:in `call'
warden-jwt_auth (0.5.0) lib/warden/jwt_auth/middleware.rb:23:in `call'
rack-attack (6.3.1) lib/rack/attack.rb:111:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.3) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.3) lib/rack/etag.rb:27:in `call'
rack (2.2.3) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.3) lib/rack/head.rb:12:in `call'
actionpack (6.0.3.2) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.3) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.3) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/cookies.rb:648:in `call'
activerecord (6.0.3.2) lib/active_record/migration.rb:567:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
activesupport (6.0.3.2) lib/active_support/callbacks.rb:101:in `run_callbacks'
actionpack (6.0.3.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
web-console (4.0.4) lib/web_console/middleware.rb:132:in `call_app'
web-console (4.0.4) lib/web_console/middleware.rb:28:in `block in call'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `catch'
web-console (4.0.4) lib/web_console/middleware.rb:17:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
lograge (0.11.2) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `block in tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (6.0.3.2) lib/active_support/tagged_logging.rb:80:in `tagged'
railties (6.0.3.2) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.3) lib/rack/method_override.rb:24:in `call'
rack (2.2.3) lib/rack/runtime.rb:22:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/static.rb:126:in `call'
rack (2.2.3) lib/rack/sendfile.rb:110:in `call'
actionpack (6.0.3.2) lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'
webpacker (5.1.1) lib/webpacker/dev_server_proxy.rb:25:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (6.0.3.2) lib/rails/engine.rb:527:in `call'
puma (4.3.5) lib/puma/configuration.rb:228:in `call'
puma (4.3.5) lib/puma/server.rb:713:in `handle_request'
puma (4.3.5) lib/puma/server.rb:472:in `process_client'
puma (4.3.5) lib/puma/server.rb:328:in `block in run'
puma (4.3.5) lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

Provide following information. Please, format pasted output as code. Feel free to remove the secret key value.

- Version of `devise-jwt` in use
0.8.0
- Version of `rails` in use
6.2
- Version of `warden-jwt_auth` in use
0.5.0
- Output of `Devise::JWT.config`
```
#<Dry::Configurable::Config values={:secret=>"99c927cefe5d1146673073a3ed1a634ee79d684e3c76f012c57c13d5a0aaf08c", :expiration_time=>2629746, :dispatch_requests=>[["POST", /^\/login$/], ["POST", /^\/login$/], ["POST", /^\/$/]], :revocation_requests=>[["DELETE", /^\/logout$/], ["DELETE", /^\/logout$/]], :aud_header=>"JWT_AUD", :request_formats=>{}}>
```
- Output of `Warden::JWTAuth.config`
```
 #<Dry::Configurable::Config values={:secret=>"99c927cefe5d1146673073a3ed1a634ee79d684e3c76f012c57c13d5a0aaf08c", :algorithm=>"HS256", :expiration_time=>2629746, :aud_header=>"JWT_AUD", :mappings=>{:user=>User (call 'User.connection' to establish a connection)}, :dispatch_requests=>[["POST", /^\/login$/], ["POST", /^\/login$/], ["POST", /^\/$/]], :revocation_requests=>[["DELETE", /^\/logout$/], ["DELETE", /^\/logout$/]], :revocation_strategies=>{:user=>User (call 'User.connection' to establish a connection)}}>
```
- Output of `Devise.mappings`
```
{:user=>
  #<Devise::Mapping:0x0000559e31aae6d0
   @class_name="User",
   @controllers={:sessions=>"sessions", :passwords=>"devise/passwords", :registrations=>"devise/registrations"},
   @failure_app=Devise::FailureApp,
   @format=nil,
   @klass=#<Devise::Getter:0x0000559e31aadf00 @name="User">,
   @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :trackable, :jwt_authenticatable],
   @path="",
   @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>:login, :sign_out=>:logout, :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel"},
   @path_prefix=nil,
   @router_name=nil,
   @routes=[:session, :password, :registration],
   @scoped_path="users",
   @sign_out_via=:delete,
   @singular=:user,
   @used_helpers=[:session, :password, :registration],
   @used_routes=[:session, :password, :registration]>}
```

**Comment by waiting-for-dev** [comment]
It doesn't seem to be an error here. This error comes from devise, which we aren't monkey patching in any way. Have you tried if this issue fixes your use case?: https://github.com/heartcombo/devise/issues/4580

**Comment by Petercopter** [comment]
@waiting-for-dev I've been testing with the upgraded gems on a branch for a few days now, and I'm not seeing that error anymore. Not sure what was happening there, maybe there was sunspots or something. Thanks! 👍  🎉

**Comment by Petercopter** [comment]
This is still a problem for me when I upgrade the gems, not really sure what the problem is. I tried again today, and even with no code changes when you start the server, you see this error. I'll try to get more information about where it might be coming from.

**Comment by waiting-for-dev** [comment]
You can see more context in https://github.com/waiting-for-dev/devise-jwt/issues if that helps to debug.

**Comment by AhmedKamal20** [comment]
also happens to me when I use the JWT token to authenticate, but when I use the cookies on the same server, it works fine, so I think it has to do with devise-jwt

**Comment by waiting-for-dev** [comment]
Closing in favor of #186
