### ISSUE TITLE
Getting an error when trying to deploy a setup in Heroku 

### ISSUE THREAD

**Issue by LucasArruda** [waiting-for-dev/devise-jwt#226]
## Expected behavior

Being able to deploy to heroku a web (not only API) that makes use of devise and `devise-jwt`

## Actual behavior

I get an error while trying to load `jwt` config in `devise` config file

```heroku
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        rake aborted!
remote:        NoMethodError: undefined method `[]' for nil:NilClass
remote:        /tmp/build_e2acb2f1/config/initializers/devise.rb:314:in `block (2 levels) in <main>'
remote:        /tmp/build_e2acb2f1/vendor/bundle/ruby/3.0.0/gems/devise-jwt-0.8.1/lib/devise/jwt.rb:21:in `jwt'
remote:        /tmp/build_e2acb2f1/config/initializers/devise.rb:313:in `block in <main>'
remote:        /tmp/build_e2acb2f1/vendor/bundle/ruby/3.0.0/gems/devise-4.8.0/lib/devise.rb:307:in `setup'
remote:        /tmp/build_e2acb2f1/config/initializers/devise.rb:11:in `<main>'
remote:        /tmp/build_e2acb2f1/vendor/bundle/ruby/3.0.0/gems/bootsnap-1.7.5/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
```

## Steps to Reproduce the Problem

1. Add and config devise-jwt 
2. Setup works locally
3. Push to heroku (get failure message)

## Debugging information

- Version of `devise-jwt` in use: `0.8.1`

- Version of `rails` in use: 6.1.4

- Output of `Devise::JWT.config`

```
Devise::JWT.config
=> #<Dry::Configurable::Config values={:secret=>"…", :expiration_time=>3600, :dispatch_requests=>[["POST", /^\/users\/sign_in$/], ["POST", /^\/users$/]], :revocation_requests=>[["DELETE", /^\/users\/sign_out$/]], :aud_header=>"JWT_AUD", :request_formats=>{}}>
```

- Output of `Warden::JWTAuth.config`

```
Warden::JWTAuth.config
=> #<Dry::Configurable::Config values={:secret=>"…", :algorithm=>"HS256", :expiration_time=>3600, :aud_header=>"JWT_AUD", :mappings=>{:user=>User(id: integer, email: string, encrypted_password: string, reset_password_token: string, reset_password_sent_at: datetime, remember_created_at: datetime, sign_in_count: integer, current_sign_in_at: datetime, last_sign_in_at: datetime, current_sign_in_ip: string, last_sign_in_ip: string, confirmation_token: string, confirmed_at: datetime, confirmation_sent_at: datetime, unconfirmed_email: string, failed_attempts: integer, unlock_token: string, locked_at: datetime, created_at: datetime, updated_at: datetime, jti: string, role: integer)}, :dispatch_requests=>[["POST", /^\/users\/sign_in$/], ["POST", /^\/users$/]], :revocation_requests=>[["DELETE", /^\/users\/sign_out$/]], :revocation_strategies=>{:user=>User(id: integer, email: string, encrypted_password: string, reset_password_token: string, reset_password_sent_at: datetime, remember_created_at: datetime, sign_in_count: integer, current_sign_in_at: datetime, last_sign_in_at: datetime, current_sign_in_ip: string, last_sign_in_ip: string, confirmation_token: string, confirmed_at: datetime, confirmation_sent_at: datetime, unconfirmed_email: string, failed_attempts: integer, unlock_token: string, locked_at: datetime, created_at: datetime, updated_at: datetime, jti: string, role: integer)}}>
```

- Output of `Devise.mappings`

```
Devise.mappings
=> {:user=>
  #<Devise::Mapping:0x00007f88f242b9b8
   @class_name="User",
   @controllers={:sessions=>"sessions", :registrations=>"registrations", :passwords=>"devise/passwords", :confirmations=>"devise/confirmations", :unlocks=>"devise/unlocks"},
   @failure_app=Devise::FailureApp,
   @format=nil,
   @klass=#<Devise::Getter:0x00007f88f242a888 @name="User">,
   @modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :lockable, :trackable, :jwt_authenticatable],
   @path="users",
   @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation", :unlock=>"unlock"},
   @path_prefix=nil,
   @router_name=nil,
   @routes=[:session, :password, :registration, :confirmation, :unlock],
   @scoped_path="users",
   @sign_out_via=:delete,
   @singular=:user,
   @used_helpers=[:session, :password, :registration, :confirmation, :unlock],
   @used_routes=[:session, :password, :registration, :confirmation, :unlock]>}
```

**Comment by LucasArruda** [comment]
I finally found the problem and why it works in development/test.

This is not an issue with `devise-jwt`, thus I am closing this.

But just to give some insight into my problem, because it was really bugging me (and maybe this can help some random person googling around?).

I thought the issue was on `jwt` being `nil` on `jwt.secret` but actually, `devise` from `Rails.application.credentials` is the culprit. At boot time, apparently `Rails.application.credentials` isn't loaded yet. 

Most codebases will not fail at that point, because you could typically have `Rails.application.credentials.some_secret`. But I had `Rails.application.credentials.devise[:jwt_secret_key]`, because I defined it on top of `devise` context. Silly mistake! 

So, changing to `Rails.application.credentials.dig(:devise, :jwt_secret_key)` does the trick (handles `devise` being `nil` in load time).
