### ISSUE TITLE
Can't get JWT token when using devise and JWT for reset password feature

### ISSUE THREAD

**Issue by ITDevMohsin** [waiting-for-dev/devise-jwt#240]
When I try to reset a password for the Rails API project, it does not send back the JWT token when I successfully change the password.

Everything is working fine and I get an Authorization Code for the signup process and even on the sign-in process without any problem but on the password reset/update feature, I never get an Authorization token upon successful password updation.

Steps:

1. The user put an email and get a code in his account.
2. User put code and get it verified and moved to next password and confirm password screen.
3. User successfully updates his password but I do not get back the Authorization code once the password gets successfully changed.

Complete Passwords Controller code:

```
 class Api::V1::Patients::PasswordsController < Devise::PasswordsController
  respond_to :json

  skip_before_action :verify_authenticity_token

  def create
    if resource_params[:email].blank?
      return render json: { error: "Email not present" }
    end
    resource_obj = resource_class.find_by(email: resource_params[:email])
    if resource_obj.present?
      token = resource_obj.generate_password_token!
      PatientMailer.with(resource: resource_obj, token: token).reset_password_token_email.deliver_now
      render json: { message: 'reset password token sent successfully' }, status: :ok
    else
      render json: { error: ['Email address not found. Please check and try again.'] }, status: :not_found
    end
  end

  def edit
    resource = resource_class.reset_password_by_token(params)
    if resource.valid?
      render json: { token: resource.reset_password_token, message: "Token is verified" }, status: :ok
    else
      render json: { token: params[:reset_password_token], message: "Token is not verified" }, status: :not_found
    end
  end

  def update
    self.resource = resource_class.reset_password_by_token(params)
    if resource.errors.empty?
      bypass_sign_in(resource, scope: :patient)
      render json: resource, root: 'data', each_serializer: PatientSerializer, message: 'Password updated successfully', adapter: :json, status: :ok
    else
      render json: { error: resource.errors.full_messages }, status: :not_found
    end
  end

  private

  def resource_params
    params.require(:patient).permit(:email, :password, :password_confirmation)
  end
end

```

Routes:

```
namespace :api, defaults: { format: :json } do
    namespace :v1 do
      devise_for :patients, controllers: {
        sessions: 'api/v1/patients/sessions',
        registrations: 'api/v1/patients/registrations',
        passwords: 'api/v1/patients/passwords'
      }

      devise_for :providers, controllers: {
        sessions: 'api/v1/providers/sessions',
        registrations: 'api/v1/providers/registrations',
        passwords: 'api/v1/providers/passwords'
      }
    end
  end
```

Config:
  
```
 config.jwt do |jwt|
    jwt.secret = ENV['DEVISE_JWT_SECRET_KEY']
    jwt.expiration_time = 30.day.to_i
    jwt.dispatch_requests = [
      ['PUT', %r{^/api/v1/patients/password$}]
    ]
  end
```

Devise Config:

` config.sign_in_after_reset_password = true`

Logs:

   ```
 Started PUT "/api/v1/patients/password" for ::1 at 2022-03-05 10:51:14 +0500
    Processing by Api::V1::Patients::PasswordsController#update as JSON
      Parameters: {"password"=>"[FILTERED]", "password_confirmation"=>"[FILTERED]", "reset_password_token"=>"[FILTERED]"}
      Patient Load (38.1ms)  SELECT "patients".* FROM "patients" WHERE "patients"."reset_password_token" = $1 ORDER BY "patients"."id" ASC LIMIT $2  [["reset_password_token", "32bbaa6ea73b7a49d1abb84c0756b4666f12f95c42c27218d3150b0204e1e909"], ["LIMIT", 1]]
      ↳ app/controllers/api/v1/patients/passwords_controller.rb:30:in `update'
      TRANSACTION (387.7ms)  BEGIN
      ↳ app/controllers/api/v1/patients/passwords_controller.rb:30:in `update'
      Patient Update (225.8ms)  UPDATE "patients" SET "encrypted_password" = $1, "reset_password_token" = $2, "reset_password_sent_at" = $3, "updated_at" = $4 WHERE "patients"."id" = $5  [["encrypted_password", "$2a$12$XYIP61byGk5XgROhYDP8WuEfn698HTRL/Rv2Y3K/Okt7esT5NyVTW"], ["reset_password_token", nil], ["reset_password_sent_at", nil], ["updated_at", "2022-03-05 05:51:15.618405"], ["id", 2]]
      ↳ app/controllers/api/v1/patients/passwords_controller.rb:30:in `update'
      TRANSACTION (100.8ms)  COMMIT
      ↳ app/controllers/api/v1/patients/passwords_controller.rb:30:in `update'
    [active_model_serializers]   Address Load (48.1ms)  SELECT "addresses".* FROM "addresses" WHERE "addresses"."addressable_id" = $1 AND "addresses"."addressable_type" = $2 LIMIT $3  [["addressable_id", 2], ["addressable_type", "Patient"], ["LIMIT", 1]]
    [active_model_serializers]   ↳ app/controllers/api/v1/patients/passwords_controller.rb:33:in `update'
    [active_model_serializers] Rendered PatientSerializer with ActiveModelSerializers::Adapter::Json (1493.45ms)
    Completed 200 OK in 6337ms (Views: 829.0ms | ActiveRecord: 1504.4ms | Allocations: 12243320)
```

Additional Information:

- Version of `devise-jwt` in use
`devise-jwt (0.9.0)`

- Version of `rails` in use
`Rails 6.1.3.1`

- Version of `warden-jwt_auth` in use
`warden-jwt_auth (~> 0.6)`

- Output of `Devise::JWT.config`
```
=> #<Dry::Configurable::Config values=
{:secret=>"e5c0e57ddeeb325602e30146f2acfedc52f32388dc1e810611367ece1f9055114738188f7d9e23e2b44250c792ede02b
e3b756f36f9c327bfefc74283869c1fd", :expiration_time=>2592000, :dispatch_requests=>[["PUT", 
/^\/api\/v1\/patients\/password$/], ["POST", /^\/api\/v1\/patients\/sign_in$/], ["POST", /^\/api\/v1\/patients$/], ["POST", 
/^\/api\/v1\/providers\/sign_in$/], ["POST", /^\/api\/v1\/providers$/], ["POST", /^\/patients\/sign_in$/], ["POST", /^\/patients$/], 
["POST", /^\/providers\/sign_in$/], ["POST", /^\/providers$/]], :revocation_requests=>[["DELETE", /^\/api\/v1\/patients\/sign_out$/], 
["DELETE", /^\/api\/v1\/providers\/sign_out$/], ["DELETE", /^\/patients\/sign_out$/], ["DELETE", /^\/providers\/sign_out$/]], 
:aud_header=>"JWT_AUD", :request_formats=>{}}>
```

- Output of `Warden::JWTAuth.config`
```
=> #<Dry::Configurable::Config values=
{:secret=>"e5c0e57ddeeb325602e30146f2acfedc52f32388dc1e810611367ece1f9055114738188f7d9e23e2b44250c792ede02b
e3b756f36f9c327bfefc74283869c1fd", :algorithm=>"HS256", :expiration_time=>2592000, :aud_header=>"JWT_AUD", 
:mappings=>{:api_v1_patient=>Patient(id: integer, encrypted_password: string, reset_password_token: string, 
reset_password_sent_at: datetime, remember_created_at: datetime, confirmation_token: string, confirmed_at: datetime, 
confirmation_sent_at: datetime, created_at: datetime, updated_at: datetime, gender: integer, picture: string, identifier: string, 
active: boolean, deleted: boolean, email_ciphertext: text, first_name_ciphertext: text, last_name_ciphertext: text, 
date_of_birth_ciphertext: text, contact_number_ciphertext: text, stripe_customer_id_ciphertext: text, 
unconfirmed_email_ciphertext: text, email_bidx: string, unconfirmed_email_bidx: string, first_name_bidx: string, last_name_bidx: 
string, jti: string, full_name: string, economic_condition: integer, social_state: integer, email: string, first_name: string, last_name: 
string, date_of_birth: date, contact_number: string, stripe_customer_id: string, unconfirmed_email: string), 
:api_v1_provider=>Provider(id: integer, encrypted_password: string, reset_password_token: string, reset_password_sent_at: 
datetime, remember_created_at: datetime, created_at: datetime, updated_at: datetime, gender: integer, profile_picture: string, 
upload_bio: string, w9_tax_form: string, professional_liability_insurance_form: string, account_status: integer, identifier: string, 
email_ciphertext: text, first_name_ciphertext: text, last_name_ciphertext: text, date_of_birth_ciphertext: text, specialty_ciphertext: 
text, provider_about_ciphertext: text, stripe_account_id_ciphertext: text, zoom_user_id_ciphertext: text, phone_ciphertext: text, 
email_bidx: string, first_name_bidx: string, last_name_bidx: string, account_notes: string, jti: string, email: string, first_name: 
string, last_name: string, date_of_birth: date, specialty: string, provider_about: string, stripe_account_id: string, zoom_user_id: 
string, phone: string), :patient=>Patient(id: integer, encrypted_password: string, reset_password_token: string, 
reset_password_sent_at: datetime, remember_created_at: datetime, confirmation_token: string, confirmed_at: datetime, 
confirmation_sent_at: datetime, created_at: datetime, updated_at: datetime, gender: integer, picture: string, identifier: string, 
active: boolean, deleted: boolean, email_ciphertext: text, first_name_ciphertext: text, last_name_ciphertext: text, 
date_of_birth_ciphertext: text, contact_number_ciphertext: text, stripe_customer_id_ciphertext: text, 
unconfirmed_email_ciphertext: text, email_bidx: string, unconfirmed_email_bidx: string, first_name_bidx: string, last_name_bidx: 
string, jti: string, full_name: string, economic_condition: integer, social_state: integer, email: string, first_name: string, last_name: 
string, date_of_birth: date, contact_number: string, stripe_customer_id: string, unconfirmed_email: string), :provider=>Provider(id: 
integer, encrypted_password: string, reset_password_token: string, reset_password_sent_at: datetime, remember_created_at: 
datetime, created_at: datetime, updated_at: datetime, gender: integer, profile_picture: string, upload_bio: string, w9_tax_form: 
string, professional_liability_insurance_form: string, account_status: integer, identifier: string, email_ciphertext: text, 
first_name_ciphertext: text, last_name_ciphertext: text, date_of_birth_ciphertext: text, specialty_ciphertext: text, 
provider_about_ciphertext: text, stripe_account_id_ciphertext: text, zoom_user_id_ciphertext: text, phone_ciphertext: text, 
email_bidx: string, first_name_bidx: string, last_name_bidx: string, account_notes: string, jti: string, email: string, first_name: 
string, last_name: string, date_of_birth: date, specialty: string, provider_about: string, stripe_account_id: string, zoom_user_id: 
string, phone: string)}, :dispatch_requests=>[["PUT", /^\/api\/v1\/patients\/password$/], ["POST", /^\/api\/v1\/patients\/sign_in$/], 
["POST", /^\/api\/v1\/patients$/], ["POST", /^\/api\/v1\/providers\/sign_in$/], ["POST", /^\/api\/v1\/providers$/], ["POST", 
/^\/patients\/sign_in$/], ["POST", /^\/patients$/], ["POST", /^\/providers\/sign_in$/], ["POST", /^\/providers$/]], 
:revocation_requests=>[["DELETE", /^\/api\/v1\/patients\/sign_out$/], ["DELETE", /^\/api\/v1\/providers\/sign_out$/], ["DELETE", 
/^\/patients\/sign_out$/], ["DELETE", /^\/providers\/sign_out$/]], :revocation_strategies=>{:api_v1_patient=>JwtBlacklist(id: 
integer, jti: string, exp: datetime, created_at: datetime, updated_at: datetime), :api_v1_provider=>JwtBlacklist(id: integer, jti: string, 
exp: datetime, created_at: datetime, updated_at: datetime), :patient=>JwtBlacklist(id: integer, jti: string, exp: datetime, created_at: 
datetime, updated_at: datetime), :provider=>JwtBlacklist(id: integer, jti: string, exp: datetime, created_at: datetime, updated_at: 
datetime)}}>
```

- Output of `Devise.mappings`
 ```
=> {:api_v1_patient=>#<Devise::Mapping:0x00007fe4d0255488 @scoped_path="api_v1/patients", @singular=:api_v1_patient, 
@class_name="Patient", @klass=#<Devise::Getter:0x00007fe4d02550c8 @name="Patient">, @path="patients", 
@path_prefix="/api/v1", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers=
{:sessions=>"api/v1/patients/sessions", :registrations=>"api/v1/patients/registrations", :passwords=>"api/v1/patients/passwords", 
:confirmations=>"api/v1/confirmations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", 
:sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation"}, 
@modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :timeoutable, 
:jwt_authenticatable], @routes=[:session, :password, :registration, :confirmation], @used_routes=[:session, :password, 
:registration, :confirmation], @used_helpers=[:session, :password, :registration, :confirmation]>, :api_v1_provider=>#
<Devise::Mapping:0x00007fe4cb3bbe30 @scoped_path="api_v1/providers", @singular=:api_v1_provider, 
@class_name="Provider", @klass=#<Devise::Getter:0x00007fe4cb3bba70 @name="Provider">, @path="providers", 
@path_prefix="/api/v1", @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers=
{:sessions=>"api/v1/providers/sessions", :registrations=>"api/v1/providers/registrations", 
:passwords=>"api/v1/providers/passwords"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", 
:sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel"}, @modules=
[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :timeoutable, :jwt_authenticatable], @routes=
[:session, :password, :registration], @used_routes=[:session, :password, :registration], @used_helpers=[:session, :password, 
:registration]>, :admin_user=>#<Devise::Mapping:0x00007fe4cecc6180 @scoped_path="admin_users", @singular=:admin_user, 
@class_name="AdminUser", @klass=#<Devise::Getter:0x00007fe4cecc5c58 @name="AdminUser">, @path="admin", 
@path_prefix=nil, @sign_out_via=[:delete, :get], @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers=
{:sessions=>"active_admin/devise/sessions", :passwords=>"active_admin/devise/passwords", 
:unlocks=>"active_admin/devise/unlocks", :registrations=>"active_admin/devise/registrations", 
:confirmations=>"active_admin/devise/confirmations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", 
:sign_in=>"login", :sign_out=>"logout", :password=>"password"}, @modules=[:database_authenticatable, :rememberable, 
:recoverable, :validatable], @routes=[:session, :password], @used_routes=[:session, :password], @used_helpers=[:session, 
:password]>, :patient=>#<Devise::Mapping:0x00007fe4d02ace68 @scoped_path="patients", @singular=:patient, 
@class_name="Patient", @klass=#<Devise::Getter:0x00007fe4d02acad0 @name="Patient">, @path="patients", 
@path_prefix=nil, @sign_out_via=:delete, @format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers=
{:registrations=>"patients/registrations", :sessions=>"patients/sessions", :passwords=>"devise/passwords", 
:confirmations=>"devise/confirmations"}, @path_names={:registration=>"", :new=>"new", :edit=>"edit", :sign_in=>"sign_in", 
:sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel", :confirmation=>"confirmation"}, 
@modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :confirmable, :timeoutable, 
:jwt_authenticatable], @routes=[:session, :password, :registration, :confirmation], @used_routes=[:session, :password, 
:registration, :confirmation], @used_helpers=[:session, :password, :registration, :confirmation]>, :provider=>#
<Devise::Mapping:0x00007fe4d02ce590 @scoped_path="providers", @singular=:provider, @class_name="Provider", @klass=#
<Devise::Getter:0x00007fe4d02ce1f8 @name="Provider">, @path="providers", @path_prefix=nil, @sign_out_via=:delete, 
@format=nil, @router_name=nil, @failure_app=Devise::FailureApp, @controllers={:registrations=>"providers/registrations", 
:sessions=>"providers/sessions", :passwords=>"devise/passwords"}, @path_names={:registration=>"", :new=>"new", 
:edit=>"edit", :sign_in=>"sign_in", :sign_out=>"sign_out", :password=>"password", :sign_up=>"sign_up", :cancel=>"cancel"}, 
@modules=[:database_authenticatable, :rememberable, :recoverable, :registerable, :validatable, :timeoutable, 
:jwt_authenticatable], @routes=[:session, :password, :registration], @used_routes=[:session, :password, :registration], 
@used_helpers=[:session, :password, :registration]>}
```

**Comment by waiting-for-dev** [comment]
It looks like you're overriding the controller too much. If you're not calling warden authentication stuff, `devise-jwt` has no way to hook into it and add the token. Please, see https://github.com/waiting-for-dev/devise-jwt/wiki/Configuring-devise-for-APIs#overwriting-controllers

**Comment by ITDevMohsin** [comment]
@waiting-for-dev I am overriding because I have all these use-cases. Also, for authentication, I am using warden authentication obviously. 
Here is the code for it:

```
class Api::V1::Patients::SessionsController < Devise::SessionsController
  respond_to :json

  skip_before_action :verify_authenticity_token

  def create
    patient = Patient.find_by(email: params[:patient][:email])
    if patient && patient.valid_password?(params[:patient][:password])
      self.resource = warden.authenticate(scope: :patient)
      sign_in(resource_name, resource)
      respond_with resource
    else
      render json: { errors: 'email or password is invalid' }, status: :unprocessable_entity
    end
  end
end
```

What else I need to do in this case? Can you please point it out? Thanks!

**Comment by waiting-for-dev** [comment]
@ITDevMohsin I'm referring to the `Api::V1::Patients::PasswordsController` you pasted above. It seems you're bypassing sign in. See https://github.com/heartcombo/devise/blob/451ff6d49c71e543962d2b29d77f2e744b2d47e1/app/controllers/devise/passwords_controller.rb#L43

**Comment by ITDevMohsin** [comment]
@waiting-for-dev Thanks for the input. 
I tried below and no error showed up nor a token with success call.
```
if resource.errors.empty?
      sign_in(resource_name, resource)
      render json: resource, root: 'data', each_serializer: PatientSerializer, message: 'Password updated successfully', adapter: :json, status: :ok
else
      render json: { error: resource.errors.full_messages }, status: :not_found
end
```
<img width="1123" alt="Screenshot 2022-03-08 at 1 18 29 PM" src="https://user-images.githubusercontent.com/21135288/157195476-1ac4269a-98cb-42f5-ac34-499da7c00628.png">

I tried:
```
if resource.errors.empty?
      self.resource = warden.authenticate(scope: :patient)
      sign_in(resource_name, resource)
      render json: resource, root: 'data', each_serializer: PatientSerializer, message: 'Password updated successfully', adapter: :json, status: :ok
else
      render json: { error: resource.errors.full_messages }, status: :not_found
end
```
and response was like that:

<img width="1036" alt="Screenshot 2022-03-08 at 1 21 25 PM" src="https://user-images.githubusercontent.com/21135288/157195950-8b28f6b7-a6fb-4e56-b636-1902172a09e9.png">

Seems like there is no way to get the token anyway!

**Comment by waiting-for-dev** [comment]
It seems you have an error on that request . Look at the `NoMethodError` line on the response screenshot.

**Comment by ITDevMohsin** [comment]
Thanks for your all input!
Nothing seems to work for me and I even fixed the `NoMethodError`. 
I am going for some other solution now.

**Comment by waiting-for-dev** [comment]
:+1: closing for now, let me know if you need more help
