### ISSUE TITLE
Desive JWT import in application.rb  throwing is error

### ISSUE THREAD

**Issue by farooqch11** [waiting-for-dev/devise-jwt#261]
```
NoMethodError: undefined method `call' for {:default=>#<Dry::Container::Registry:0x0000000106decfe0 @_mutex=#<Thread::Mutex:0x0000000106decd88>>}:Hash

        config.registry.call(_container, key, item, options)
                       ^^^^^

```

**Comment by farooqch11** [comment]
if we dont import rails 7 throws this error 

```
rails aborted!
NoMethodError: undefined method `call' for {:default=>#<Dry::Container::Registry:0x00000001141a02b0 @_mutex=#<Thread::Mutex:0x00000001141a0238>>}:Hash

        config.registry.call(_container, key, item, options)
                       ^^^^^
/Users/macbookpro/Desktop/development/dashboard/config/application.rb:11:in `<top (required)>'
/Users/macbookpro/Desktop/development/dashboard/Rakefile:4:in `require'
/Users/macbookpro/Desktop/development/dashboard/Rakefile:4:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'

Caused by:
LoadError: cannot load such file -- devise-jwt
/Users/macbookpro/Desktop/development/dashboard/config/application.rb:11:in `<top (required)>'
/Users/macbookpro/Desktop/development/dashboard/Rakefile:4:in `require'
/Users/macbookpro/Desktop/development/dashboard/Rakefile:4:in `<top (required)>'
bin/rails:4:in `require'
bin/rails:4:in `<main>'
(See full trace by running task with --trace)
```

**Comment by waiting-for-dev** [comment]
Thanks for reporting and sorry for the late reply. I'll take a look into it as soon as possible. In the meantime, any help is appreciated!

**Comment by waiting-for-dev** [comment]
I'm closing it as nobody else reported it in a long time, so I don't think there's any issue with Rails 7 compatibility. Please, provide a reproducing repo if still an issue 🙏
