### ISSUE TITLE
Undefined method "update_column" when sign_out

### ISSUE THREAD

**Issue by xdef** [waiting-for-dev/devise-jwt#36]
Hi, I use devise 4.3.0, devise-jwt 3.0 with mongoid 6.2.0. My auth model is Client. 
When I try to logout,  I receive the fallowing error:
```
NoMethodError (undefined method `update_column' for #<Client:0x007f864e99b548>
Did you mean?  updateable?):
  
devise-jwt (0.3.0) lib/devise/jwt/revocation_strategies/jti_matcher.rb:29:in `revoke_jwt'
warden-jwt_auth (0.1.3) lib/warden/jwt_auth/token_revoker.rb:16:in `call'
warden-jwt_auth (0.1.3) lib/warden/jwt_auth/middleware/revocation_manager.rb:30:in `revoke_token'
warden-jwt_auth (0.1.3) lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
rack (2.0.3) lib/rack/builder.rb:153:in `call'
warden-jwt_auth (0.1.3) lib/warden/jwt_auth/middleware.rb:23:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `catch'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.3) lib/rack/etag.rb:25:in `call'
rack (2.0.3) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.3) lib/rack/head.rb:12:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'
activesupport (5.1.3) lib/active_support/callbacks.rb:97:in `run_callbacks'
actionpack (5.1.3) lib/action_dispatch/middleware/callbacks.rb:24:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
railties (5.1.3) lib/rails/rack/logger.rb:36:in `call_app'
railties (5.1.3) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.1.3) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.1.3) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.1.3) lib/rails/rack/logger.rb:24:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
request_store_rails (1.0.3) lib/request_store_rails/middleware.rb:17:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/request_id.rb:25:in `call'
rack (2.0.3) lib/rack/runtime.rb:22:in `call'
activesupport (5.1.3) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.1.3) lib/action_dispatch/middleware/static.rb:125:in `call'
rack (2.0.3) lib/rack/sendfile.rb:111:in `call'
railties (5.1.3) lib/rails/engine.rb:522:in `call'
puma (3.9.1) lib/puma/configuration.rb:224:in `call'
puma (3.9.1) lib/puma/server.rb:602:in `handle_request'
puma (3.9.1) lib/puma/server.rb:435:in `process_client'
puma (3.9.1) lib/puma/server.rb:299:in `block in run'
puma (3.9.1) lib/puma/thread_pool.rb:120:in `block in spawn_thread'
```

This happens because there is no method 'update_column' in Mongoid.

**Comment by waiting-for-dev** [comment]
That method is fired in the `JTIMatcher` revocation strategy, which is intended to be included in an `ActiveRecord` model. This gem only comes with `ActiveRecord` support out of the box. However, it will be straightforward for you to define a [custom revocation strategy](https://github.com/waiting-for-dev/devise-jwt#custom-strategies) based on [`JTIMatcher`](https://github.com/waiting-for-dev/devise-jwt/blob/master/lib/devise/jwt/revocation_strategies/jti_matcher.rb) but adapted for Mongoid.

**Comment by xdef** [comment]
Thank you for your quick response

**Comment by waiting-for-dev** [comment]
Feel free to come back with any question regarding the revocation strategy implementation :+1:
