### ISSUE TITLE
Authentication not working for me

### ISSUE THREAD

**Issue by mariuszmikolajczak** [waiting-for-dev/devise-jwt#65]
Hi,
I followed guide (README file) to install this gem but failed. Next I tried to use some existing rails app with this gem:
https://github.com/rchuasing/rails-api-boilerplate

I stopped on both tries in this same point. 

When I request GET to /users/sign_in, recieved:

```
Showing /home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/app/views/devise/sessions/new.html.erb where line #3 raised:

undefined method `protect_against_forgery?' for #<#<Class:0x00555ad2fe21a8>:0x00555ad2fe1820>
```
```ruby

        def token_tag(token = nil, form_options: {})
          if token != false && protect_against_forgery?
            token ||= form_authenticity_token(form_options: form_options)
            tag(:input, type: "hidden", name: request_forgery_protection_token.to_s, value: token)
          else
```

I manually created User in rails console
```ruby
User.create!(email: 'mariusz@example.com', password: '123qwe')
```
Then I tried to login by request POST on /users/sign_in with body
```
{"email": "mariusz@example.com", "password": "123qwe"}
```
API returned:
```
{
    "status": 500,
    "error": "Internal Server Error",
    "exception": "#<NoMethodError: undefined method `flash' for #<ActionDispatch::Request:0x00555ad302b650>>",
    "traces": {
        "Application Trace": [],
        "Framework Trace": [
            {
                "id": 0,
                "trace": "/home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/lib/devise/failure_app.rb:17:in `flash'"
            },
            {
                "id": 1,
                "trace": "/home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/lib/devise/failure_app.rb:71:in `recall'"
            },
            {
                "id": 2,
                "trace": "/home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/lib/devise/failure_app.rb:39:in `respond'"
            },
            {
                "id": 3,
                "trace": "actionpack (5.1.0) lib/abstract_controller/base.rb:186:in `process_action'"
            },
            {
                "id": 4,
                "trace": "actionpack (5.1.0) lib/abstract_controller/base.rb:124:in `process'"
            },
            {
                "id": 5,
                "trace": "actionpack (5.1.0) lib/action_controller/metal.rb:189:in `dispatch'"
            },
            {
                "id": 6,
                "trace": "actionpack (5.1.0) lib/action_controller/metal.rb:242:in `block in action'"
            },
            {
                "id": 7,
                "trace": "/home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/lib/devise/failure_app.rb:21:in `call'"
            },
            {
                "id": 8,
                "trace": "/home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/lib/devise/delegator.rb:5:in `call'"
            },
            {
                "id": 9,
                "trace": "warden (1.2.7) lib/warden/manager.rb:143:in `call_failure_app'"
            },
            {
                "id": 10,
                "trace": "warden (1.2.7) lib/warden/manager.rb:129:in `process_unauthenticated'"
            },
            {
                "id": 11,
                "trace": "warden (1.2.7) lib/warden/manager.rb:44:in `call'"
            },
            {
                "id": 12,
                "trace": "rack (2.0.1) lib/rack/etag.rb:25:in `call'"
            },
            {
                "id": 13,
                "trace": "rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'"
            },
            {
                "id": 14,
                "trace": "rack (2.0.1) lib/rack/head.rb:12:in `call'"
            },
            {
                "id": 15,
                "trace": "activerecord (5.1.0) lib/active_record/migration.rb:556:in `call'"
            },
            {
                "id": 16,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'"
            },
            {
                "id": 17,
                "trace": "activesupport (5.1.0) lib/active_support/callbacks.rb:97:in `run_callbacks'"
            },
            {
                "id": 18,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/callbacks.rb:24:in `call'"
            },
            {
                "id": 19,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'"
            },
            {
                "id": 20,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'"
            },
            {
                "id": 21,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"
            },
            {
                "id": 22,
                "trace": "railties (5.1.0) lib/rails/rack/logger.rb:36:in `call_app'"
            },
            {
                "id": 23,
                "trace": "railties (5.1.0) lib/rails/rack/logger.rb:24:in `block in call'"
            },
            {
                "id": 24,
                "trace": "activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `block in tagged'"
            },
            {
                "id": 25,
                "trace": "activesupport (5.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'"
            },
            {
                "id": 26,
                "trace": "activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `tagged'"
            },
            {
                "id": 27,
                "trace": "railties (5.1.0) lib/rails/rack/logger.rb:24:in `call'"
            },
            {
                "id": 28,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"
            },
            {
                "id": 29,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/request_id.rb:25:in `call'"
            },
            {
                "id": 30,
                "trace": "rack (2.0.1) lib/rack/runtime.rb:22:in `call'"
            },
            {
                "id": 31,
                "trace": "activesupport (5.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'"
            },
            {
                "id": 32,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'"
            },
            {
                "id": 33,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/static.rb:125:in `call'"
            },
            {
                "id": 34,
                "trace": "rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"
            },
            {
                "id": 35,
                "trace": "railties (5.1.0) lib/rails/engine.rb:522:in `call'"
            },
            {
                "id": 36,
                "trace": "puma (3.8.2) lib/puma/configuration.rb:224:in `call'"
            },
            {
                "id": 37,
                "trace": "puma (3.8.2) lib/puma/server.rb:600:in `handle_request'"
            },
            {
                "id": 38,
                "trace": "puma (3.8.2) lib/puma/server.rb:435:in `process_client'"
            },
            {
                "id": 39,
                "trace": "puma (3.8.2) lib/puma/server.rb:299:in `block in run'"
            },
            {
                "id": 40,
                "trace": "puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"
            }
        ],
        "Full Trace": [
            {
                "id": 0,
                "trace": "/home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/lib/devise/failure_app.rb:17:in `flash'"
            },
            {
                "id": 1,
                "trace": "/home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/lib/devise/failure_app.rb:71:in `recall'"
            },
            {
                "id": 2,
                "trace": "/home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/lib/devise/failure_app.rb:39:in `respond'"
            },
            {
                "id": 3,
                "trace": "actionpack (5.1.0) lib/abstract_controller/base.rb:186:in `process_action'"
            },
            {
                "id": 4,
                "trace": "actionpack (5.1.0) lib/abstract_controller/base.rb:124:in `process'"
            },
            {
                "id": 5,
                "trace": "actionpack (5.1.0) lib/action_controller/metal.rb:189:in `dispatch'"
            },
            {
                "id": 6,
                "trace": "actionpack (5.1.0) lib/action_controller/metal.rb:242:in `block in action'"
            },
            {
                "id": 7,
                "trace": "/home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/lib/devise/failure_app.rb:21:in `call'"
            },
            {
                "id": 8,
                "trace": "/home/mariusz/.rvm/gems/ruby-2.4.1@pragdev-boilerplate/bundler/gems/devise-a62faa2c8258/lib/devise/delegator.rb:5:in `call'"
            },
            {
                "id": 9,
                "trace": "warden (1.2.7) lib/warden/manager.rb:143:in `call_failure_app'"
            },
            {
                "id": 10,
                "trace": "warden (1.2.7) lib/warden/manager.rb:129:in `process_unauthenticated'"
            },
            {
                "id": 11,
                "trace": "warden (1.2.7) lib/warden/manager.rb:44:in `call'"
            },
            {
                "id": 12,
                "trace": "rack (2.0.1) lib/rack/etag.rb:25:in `call'"
            },
            {
                "id": 13,
                "trace": "rack (2.0.1) lib/rack/conditional_get.rb:38:in `call'"
            },
            {
                "id": 14,
                "trace": "rack (2.0.1) lib/rack/head.rb:12:in `call'"
            },
            {
                "id": 15,
                "trace": "activerecord (5.1.0) lib/active_record/migration.rb:556:in `call'"
            },
            {
                "id": 16,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/callbacks.rb:26:in `block in call'"
            },
            {
                "id": 17,
                "trace": "activesupport (5.1.0) lib/active_support/callbacks.rb:97:in `run_callbacks'"
            },
            {
                "id": 18,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/callbacks.rb:24:in `call'"
            },
            {
                "id": 19,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'"
            },
            {
                "id": 20,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/debug_exceptions.rb:59:in `call'"
            },
            {
                "id": 21,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'"
            },
            {
                "id": 22,
                "trace": "railties (5.1.0) lib/rails/rack/logger.rb:36:in `call_app'"
            },
            {
                "id": 23,
                "trace": "railties (5.1.0) lib/rails/rack/logger.rb:24:in `block in call'"
            },
            {
                "id": 24,
                "trace": "activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `block in tagged'"
            },
            {
                "id": 25,
                "trace": "activesupport (5.1.0) lib/active_support/tagged_logging.rb:26:in `tagged'"
            },
            {
                "id": 26,
                "trace": "activesupport (5.1.0) lib/active_support/tagged_logging.rb:69:in `tagged'"
            },
            {
                "id": 27,
                "trace": "railties (5.1.0) lib/rails/rack/logger.rb:24:in `call'"
            },
            {
                "id": 28,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'"
            },
            {
                "id": 29,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/request_id.rb:25:in `call'"
            },
            {
                "id": 30,
                "trace": "rack (2.0.1) lib/rack/runtime.rb:22:in `call'"
            },
            {
                "id": 31,
                "trace": "activesupport (5.1.0) lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'"
            },
            {
                "id": 32,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/executor.rb:12:in `call'"
            },
            {
                "id": 33,
                "trace": "actionpack (5.1.0) lib/action_dispatch/middleware/static.rb:125:in `call'"
            },
            {
                "id": 34,
                "trace": "rack (2.0.1) lib/rack/sendfile.rb:111:in `call'"
            },
            {
                "id": 35,
                "trace": "railties (5.1.0) lib/rails/engine.rb:522:in `call'"
            },
            {
                "id": 36,
                "trace": "puma (3.8.2) lib/puma/configuration.rb:224:in `call'"
            },
            {
                "id": 37,
                "trace": "puma (3.8.2) lib/puma/server.rb:600:in `handle_request'"
            },
            {
                "id": 38,
                "trace": "puma (3.8.2) lib/puma/server.rb:435:in `process_client'"
            },
            {
                "id": 39,
                "trace": "puma (3.8.2) lib/puma/server.rb:299:in `block in run'"
            },
            {
                "id": 40,
                "trace": "puma (3.8.2) lib/puma/thread_pool.rb:120:in `block in spawn_thread'"
            }
        ]
    }
}
```
Am I doing something wrong?

Best regards,
Mariusz

**Comment by mariuszmikolajczak** [comment]
This project is working like a charm:
https://github.com/jgonzalezd/rails_5_api_boilerplate
